CUDA_VISIBLE_DEVICES=1 python3 e2e_scene_dialogue_alignment_finetuning.py \
    --output_dir="./save/ambiguous_candidates/e2e-scene-dialogue/detr-bert" --cache_dir="./cache/ambiguous_candidates/e2e-scene-dialogue/detr-bert" \
    --text_model_name_or_path="bert-base-uncased" \
    --vision_model_name_or_path="facebook/detr-resnet-50" \
    --train_dataset_path='./preprocessed_data/ambiguous_candidates/simmc2.1_ambiguous_candidates_dstc11_train.json' \
    --dev_dataset_path='./preprocessed_data/ambiguous_candidates/simmc2.1_ambiguous_candidates_dstc11_dev.json' \
    --devtest_dataset_path='./preprocessed_data/ambiguous_candidates/simmc2.1_ambiguous_candidates_dstc11_devtest.json' \
    --per_device_train_batch_size=8 --per_device_eval_batch_size=8 --num_train_epochs=200 --fp16=True \
    --save_strategy="epoch" --save_steps=1 --save_total_limit=1 --load_best_model_at_end=True \
    --logging_strategy="epoch" --logging_steps=1 --report_to="tensorboard" \
    --evaluation_strategy="epoch" --eval_steps=1 --eval_accumulation_steps=1 \
    --seed=42 --dataloader_num_workers=16 \
    --gradient_accumulation_steps=1 --learning_rate=1e-4 --no_remove_unused_columns \
    --overwrite_output_dir --max_seq_length=512